FROM alpine
WORKDIR /
RUN echo -e "http://nl.alpinelinux.org/alpine/v3.9/main/" > /etc/apk/repositories
# install mosquitto client
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf && \
    apk update && \
    apk add mosquitto-clients

CMD ping 172.18.0.2
CMD mosquitto_sub -h 172.18.0.2 -t tx2/face

# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_id>
# 172.18.0.2
