FROM alpine
WORKDIR /
RUN echo -e "http://nl.alpinelinux.org/alpine/v3.9/main/" > /etc/apk/repositories
# install mosquitto client
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf && \
    apk update && \
    apk add mosquitto-clients

CMD ping mqtt_broker
CMD mosquitto_sub -h mqtt_broker -t tx2/face
