FROM alpine
WORKDIR /
RUN echo -e "http://nl.alpinelinux.org/alpine/v3.9/main/" > /etc/apk/repositories
# install mosquitto broker
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf && \
    apk update && \
    apk add mosquitto

# run mosquitto
CMD /usr/sbin/mosquitto

# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' <container_id>
# mqtt_broker tx2 address = 172.18.0.2
# mqtt_broker x86 address = 172.19.0.2